import matplotlib
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from PyQt5 import QtCore, QtGui, QtWidgets

matplotlib.use('Qt5Agg')


class MainWindowInterface(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.action_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_button.sizePolicy().hasHeightForWidth())
        self.action_button.setSizePolicy(sizePolicy)
        self.action_button.setObjectName("action_button")
        self.horizontalLayout.addWidget(self.action_button)
        self.task_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.task_combobox.setObjectName("task_combobox")
        self.horizontalLayout.addWidget(self.task_combobox)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.project_editor_button = QtWidgets.QPushButton(self.centralwidget)
        self.project_editor_button.setObjectName("project_editor_button")
        self.horizontalLayout.addWidget(self.project_editor_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.records_list = QtWidgets.QListWidget(self.centralwidget)
        self.records_list.setObjectName("records_list")
        self.verticalLayout.addWidget(self.records_list)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TimeTracker - Главное окно"))
        self.action_button.setText(_translate("MainWindow", "Старт"))
        self.time_label.setText(_translate("MainWindow", "00:00:00"))
        self.project_editor_button.setText(_translate("MainWindow", "Редактировать проекты"))


class ProjectEditDialogInterface(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 120)
        Dialog.setMinimumSize(QtCore.QSize(400, 120))
        Dialog.setMaximumSize(QtCore.QSize(400, 120))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_label = QtWidgets.QLabel(Dialog)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание проекта"))
        Dialog.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Тут вы можете создать новый проект</p></body></html>"))
        self.name_label.setText(_translate("Dialog", "Название:"))
        self.create_button.setText(_translate("Dialog", "Применить"))


class ProjectListWidgetInterface(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(0, 0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.duration_label = QtWidgets.QLabel(Form)
        self.duration_label.setText("")
        self.duration_label.setObjectName("duration_label")
        self.verticalLayout.addWidget(self.duration_label)
        self.tasks_label = QtWidgets.QLabel(Form)
        self.tasks_label.setText("")
        self.tasks_label.setObjectName("tasks_label")
        self.verticalLayout.addWidget(self.tasks_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


class ProjectInfoDialogInterface(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_button = QtWidgets.QPushButton(Dialog)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout_2.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(Dialog)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tasks_list = QtWidgets.QListWidget(Dialog)
        self.tasks_list.setObjectName("tasks_list")
        self.verticalLayout.addWidget(self.tasks_list)
        # Далее создаются фигура и холст для графиков
        figure = Figure()
        self.chart_widget = FigureCanvasQTAgg(figure)
        self.chart_widget.axes = figure.add_subplot(111)
        self.verticalLayout.addWidget(self.chart_widget)
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Просмотр проекта"))
        self.name_label.setText(_translate("Dialog", "Проект"))
        self.edit_button.setText(_translate("Dialog", "Изменить"))
        self.delete_button.setText(_translate("Dialog", "Удалить"))
        self.label.setText(_translate("Dialog", "Подзадачи"))
        self.create_button.setText(_translate("Dialog", "Создать новую подзадачу"))


class SessionListWidgetInterface(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 88)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.duration_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_label.sizePolicy().hasHeightForWidth())
        self.duration_label.setSizePolicy(sizePolicy)
        self.duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.duration_label.setObjectName("duration_label")
        self.verticalLayout.addWidget(self.duration_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.start_time_label = QtWidgets.QLabel(Form)
        self.start_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_time_label.setObjectName("start_time_label")
        self.gridLayout.addWidget(self.start_time_label, 0, 0, 1, 1)
        self.project_label = QtWidgets.QLabel(Form)
        self.project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_label.setObjectName("project_label")
        self.gridLayout.addWidget(self.project_label, 1, 1, 1, 1)
        self.task_label = QtWidgets.QLabel(Form)
        self.task_label.setAlignment(QtCore.Qt.AlignCenter)
        self.task_label.setObjectName("task_label")
        self.gridLayout.addWidget(self.task_label, 1, 0, 1, 1)
        self.end_time_label = QtWidgets.QLabel(Form)
        self.end_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.end_time_label.setObjectName("end_time_label")
        self.gridLayout.addWidget(self.end_time_label, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.duration_label.setText(_translate("Form", "Длительность:"))
        self.start_time_label.setText(_translate("Form", "Дата начала:"))
        self.project_label.setText(_translate("Form", "Проект:"))
        self.task_label.setText(_translate("Form", "Задача:"))
        self.end_time_label.setText(_translate("Form", "Дата окончания:"))


class TaskInfoDialogInterface(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_button = QtWidgets.QPushButton(Dialog)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(Dialog)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        # Далее создаётся фигура и холст для графиков
        figure = Figure()
        self.chart_widget = FigureCanvasQTAgg(figure)
        self.chart_widget.axes = figure.add_subplot(111)
        self.verticalLayout.addWidget(self.chart_widget)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Просмотр подзадачи"))
        self.name_label.setText(_translate("Dialog", "Подзадача"))
        self.edit_button.setText(_translate("Dialog", "Изменить"))
        self.delete_button.setText(_translate("Dialog", "Удалить"))
        self.label_2.setText(_translate("Dialog", "График работы"))


class ProjectEditorDialogInterface(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setDefault(False)
        self.create_button.setFlat(False)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        self.projects_list = QtWidgets.QListWidget(Dialog)
        self.projects_list.setObjectName("projects_list")
        self.verticalLayout.addWidget(self.projects_list)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактор проектов"))
        self.create_button.setText(_translate("Dialog", "Создать новый проект"))


class TaskEditDialogInterface(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 147)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(7, 7, 7, 7)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.color_label = QtWidgets.QLabel(Dialog)
        self.color_label.setObjectName("color_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.color_label)
        self.color_edit = QtWidgets.QLineEdit(Dialog)
        self.color_edit.setDragEnabled(False)
        self.color_edit.setObjectName("color_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.color_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование задачи"))
        self.error_label.setText(_translate("Dialog", "Нажмите Ctrl + G чтобы открыть средство для подбора цвета"))
        self.name_label.setText(_translate("Dialog", "Название подзадачи:"))
        self.color_label.setText(_translate("Dialog", "Цвет подзадачи:"))
        self.create_button.setText(_translate("Dialog", "Применить"))


class TaskListWidgetInterface(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 72)
        self.formLayout_2 = QtWidgets.QFormLayout(Form)
        self.formLayout_2.setObjectName("formLayout_2")
        self.picture_label = QtWidgets.QLabel(Form)
        self.picture_label.setText("")
        self.picture_label.setObjectName("picture_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.picture_label)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setObjectName("name_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_label)
        self.state_checkbox = QtWidgets.QCheckBox(Form)
        self.state_checkbox.setObjectName("state_checkbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.state_checkbox)
        self.duration_label = QtWidgets.QLabel(Form)
        self.duration_label.setObjectName("duration_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.duration_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "Название"))
        self.state_checkbox.setText(_translate("Form", "Завершено"))
        self.duration_label.setText(_translate("Form", "Затраченное время"))
